### ISSUE TITLE
Сделать Базу Данных (PostgreSQL)

### ISSUE THREAD

**Issue by hoopengo** [hoopengo/oceanplace#1]
## TODO
- [ ] [Построить структуру БД](https://dbdiagram.io/home) 

![image](https://user-images.githubusercontent.com/51020615/159291477-1c2894d8-a3d2-4adf-8d2e-5e35bd7288ee.png)
- [ ] Создание моделей БД с помощью [SQLAchemy](https://youtu.be/eXj1gdDLKho) (server/server/db/base.py)
- [ ] Настройка БД под наши нужды

Можно обратить внимание на это  [**видео.**](https://youtu.be/Lj7ivxUvSog) [Исходники](https://github.com/ianrufus/youtube/tree/main/fastapi-database)

**Comment by denvyugo** [comment]
Названия таблиц во множественном числе, поэтому таблицу User переименовать Users думаю надо.
Добавить справочную таблицу для типов продуктов (таблица Products, поле Type) или вообще убрать это поле, если не ясно для чего оно.
